version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "quotes-api-newrelic-poc"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1181zvarhsmec"
s3_prefix = "quotes-api-newrelic-poc"
region = "us-east-1"
profile = "sbx"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CreatorTag=\"Adam McQuistan\" ProjectTag=\"New Relic Serverless POC\""
