AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  quotes-api-new-relic

  Sample SAM Template for quotes-api-new-relic

Globals:
  Function:
    Timeout: 30
    Runtime: python3.8

Parameters:
  CreatorTag:
    Default: "Adam McQuistan"
    Type: String
  ProjectTag:
    Default: "New Relic Serverless POC"
    Type: String
  NewRelicAcctID:
    Type: String
    Description: "New Relic Account ID"
    AllowedPattern: '[0-9]+'
  SecretsMgrArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: newrelic-secret-key-policy


# New Relic setup taken from these web examples
# - https://github.com/newrelic/newrelic-lambda-extension/blob/main/examples/sam/python/template.yaml
# - https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking/#the-infrastructure-ui
Resources:
  GenerateQuoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/generate_quote/
      Handler: newrelic_lambda_wrapper.handler
      Environment:
        Variables:
          QUOTES_TABLE: !Ref QuotesTable
          NEW_RELIC_LAMBDA_HANDLER: api.lambda_handler
          NEW_RELIC_ACCOUNT_ID: !Ref NewRelicAcctID
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref QuotesTable
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref SecretsMgrArn
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:451483290750:layer:NewRelicPython38:39
      Tags:
        Creator: !Ref CreatorTag
        Project: !Ref ProjectTag
      Events:
        QuotesApi:
          Type: Api
          Properties:
            Path: /quotes
            Method: post

  GenerateQuoteFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GenerateQuoteFunction}"
      RetentionInDays: 3

  FavoriteQuoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/favorite_quote/
      Handler: newrelic_lambda_wrapper.handler
      Environment:
        Variables:
          QUOTES_TABLE: !Ref QuotesTable
          FAVORITE_QUOTES_TABLE: !Ref FavoriteQuotesTable
          NEW_RELIC_LAMBDA_HANDLER: api.lambda_handler
          NEW_RELIC_ACCOUNT_ID: !Ref NewRelicAcctID
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FavoriteQuotesTable
        - DynamoDBReadPolicy:
            TableName: !Ref QuotesTable
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref SecretsMgrArn
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:451483290750:layer:NewRelicPython38:39
      Tags:
        Creator: !Ref CreatorTag
        Project: !Ref ProjectTag
      Events:
        QuotesApi:
          Type: Api
          Properties:
            Path: /favorites
            Method: post

  FavoriteQuoteFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${FavoriteQuoteFunction}"
      RetentionInDays: 3

  FavoriteQuotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/fetch_quotes/
      Handler: newrelic_lambda_wrapper.handler
      Environment:
        Variables:
          QUOTES_TABLE: !Ref QuotesTable
          FAVORITE_QUOTES_TABLE: !Ref FavoriteQuotesTable
          NEW_RELIC_LAMBDA_HANDLER: api.lambda_handler
          NEW_RELIC_ACCOUNT_ID: !Ref NewRelicAcctID
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref FavoriteQuotesTable
        - DynamoDBReadPolicy:
            TableName: !Ref QuotesTable
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref SecretsMgrArn
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:451483290750:layer:NewRelicPython38:39
      Tags:
        Creator: !Ref CreatorTag
        Project: !Ref ProjectTag
      Events:
        QuotesApi:
          Type: Api
          Properties:
            Path: /favorites
            Method: get

  FavoriteQuotesFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${FavoriteQuotesFunction}"
      RetentionInDays: 3


  QuotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: quotes
      AttributeDefinitions:
        - AttributeName: "id" # id is SHA 256 Hash of author + text
          AttributeType: "S"
        - AttributeName: "author"
          AttributeType: "S"
        - AttributeName: "text"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: "quotesbyauthor"
          KeySchema:
            - AttributeName: "author"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: "quotesbytext"
          KeySchema:
            - AttributeName: "text"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      Tags:
        - Key: Creator
          Value: !Ref CreatorTag
        - Key: Project
          Value: !Ref ProjectTag

  FavoriteQuotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: favoritequotes
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: "S"
        - AttributeName: "quoteid"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "username"
          KeyType: "HASH"
        - AttributeName: "quoteid"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: Creator
          Value: !Ref CreatorTag
        - Key: Project
          Value: !Ref ProjectTag


Outputs:
  QuotesGenerationApi:
    Description: "API Gateway endpoint URL for Prod stage for Quotes generation API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/quotes"
  FavoriteQuotesApi:
    Description: "API Gateway endpoint URL for Prod stage for Quotes generation API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/favorites"
